pagopa/elasticcloud-infra

src/06_elastic_resources_common/01_snapshot.tf, src/06_elastic_resources_common/99_variables.tf, src/06_elastic_resources_common/README.md, src/06_elastic_resources_common/env/pagopa-dev/terraform.tfvars
=> feat: Added snapshot policy configuration

src/06_elastic_resources_common/02_role_definitions.tf
=> fix: Permission apm

src/07_elastic_resources_app/02_elastic_app_resources.tf
=> feat: Fixed apm data view id

src/07_elastic_resources_app/products/README.md
=> feat: Added some doc

.devops/az-app-code-review-pipelines.yml, .devops/az-app-deploy-pipelines.yml, .devops/base-code-review-pipelines.yml, .devops/base-deploy-pipelines.yml, .devops/elastic-deployment-code-review-pipelines.yml, .devops/elastic-deployment-deploy-pipelines.yml, .devops/elastic-org-code-review-pipelines.yml, .devops/elastic-org-deploy-pipelines.yml, .devops/elastic-secret-code-review-pipelines.yml, .devops/elastic-secret-deploy-pipelines.yml, .devops/org-secret-code-review-pipelines.yml, .devops/org-secret-deploy-pipelines.yml, .devops/res-app-code-review-pipelines.yml, .devops/res-app-deploy-pipelines.yml, .devops/res-common-code-review-pipelines.yml, .devops/res-common-deploy-pipelines.yml, .devops/state-storage-code-review-pipelines.yml, .devops/state-storage-deploy-pipelines.yml, .github/PULL_REQUEST_TEMPLATE.md
=> feat: Azdo pipeline

src/07_elastic_resources_app/03_default_template_customization.tf, src/07_elastic_resources_app/99_variables.tf, src/07_elastic_resources_app/README.md, src/07_elastic_resources_app/env/pagopa-dev/terraform.tfvars
Checklist based on the documentation provided [here](../src/07_elastic_resources_app/products/README.md) 
---
=> feat: Refactor default ilm config

.github/PULL_REQUEST_TEMPLATE.md
Checklist based on the documentation provided [here](../src/07_elastic_resources_app/products/README.md) 
---
=> feat: Fix pr template

src/07_elastic_resources_app/99_main.tf, src/07_elastic_resources_app/README.md, src/07_elastic_resources_app/products/README.md, src/07_elastic_resources_app/products/pagopa/ecommerce/ecommerce/appSettings.json, src/07_elastic_resources_app/products/pagopa/fdr/pagopafdr/appSettings.json, src/07_elastic_resources_app/products/pagopa/gps/pagopapaymentspull/appSettings.json, src/07_elastic_resources_app/products/pagopa/ndp/nodo/appSettings.json, src/07_elastic_resources_app/products/pagopa/ndp/nodocron/appSettings.json, src/07_elastic_resources_app/products/pagopa/ndp/nodocronreplica/appSettings.json, src/07_elastic_resources_app/products/pagopa/ndp/nodoreplica/appSettings.json, src/07_elastic_resources_app/products/pagopa/ndp/pagopastandinmanager/appSettings.json, src/07_elastic_resources_app/products/pagopa/ndp/pagopawebbo/appSettings.json, src/07_elastic_resources_app/products/pagopa/ndp/pagopawfespwfesp/appSettings.json, src/07_elastic_resources_app/products/pagopa/ndp/pagopawispconverter/appSettings.json, src/07_elastic_resources_app/products/pagopa/ndp/tech-support/appSettings.json, src/07_elastic_resources_app/products/pagopa/ndp/wispsoapconverter/appSettings.json, src/07_elastic_resources_app/products/pagopa/pagopa/pagopa/appSettings.json, src/07_elastic_resources_app/products/pagopa/paywallet/paywallet/appSettings.json, src/07_elastic_resources_app/products/pagopa/printit/printit/appSettings.json
=> feat: Upgrade data view setup

.github/PULL_REQUEST_TEMPLATE.md, src/06_elastic_resources_common/05_agent.tf, src/06_elastic_resources_common/99_main.tf, src/06_elastic_resources_common/99_variables.tf, src/06_elastic_resources_common/README.md, src/06_elastic_resources_common/env/pagopa-dev/terraform.tfvars
=> feat: Add agent taint toleration

src/07_elastic_resources_app/99_main.tf, src/07_elastic_resources_app/README.md
=> feat: Upgraded app resources module

src/06_elastic_resources_common/01_snapshot.tf, src/06_elastic_resources_common/99_variables.tf, src/07_elastic_resources_app/04_ilm.tf, src/07_elastic_resources_app/99_variables.tf, src/07_elastic_resources_app/README.md, src/07_elastic_resources_app/default_library/ilm/w2-c4-d5.json, src/07_elastic_resources_app/default_library/ilm/w2-c4-d7.json
=> feat: Fix snapshot policy

src/06_elastic_resources_common/env/pagopa-dev/terraform.tfvars
=> feat: Added printit logs

.devops/az-app-code-review-pipelines.yml, .devops/az-app-deploy-pipelines.yml, .devops/base-deploy-pipelines.yml, .devops/devops-code-review-pipelines.yml, .devops/devops-deploy-pipelines.yml, .devops/elastic-deployment-code-review-pipelines.yml, .devops/elastic-deployment-deploy-pipelines.yml, .devops/elastic-org-code-review-pipelines.yml, .devops/elastic-org-deploy-pipelines.yml, .devops/elastic-resource-deployment-code-review-pipelines.yml, .devops/elastic-resource-deployment-deploy-pipelines.yml, .devops/elastic-secret-code-review-pipelines.yml, .devops/elastic-secret-deploy-pipelines.yml, .devops/org-secret-code-review-pipelines.yml, .devops/org-secret-deploy-pipelines.yml, .devops/res-app-code-review-pipelines.yml, .devops/res-app-deploy-pipelines.yml, .devops/res-common-code-review-pipelines.yml, .devops/res-common-deploy-pipelines.yml, .devops/state-storage-code-review-pipelines.yml, .devops/state-storage-deploy-pipelines.yml
=> feat: Update deploy pipelines

src/04_elastic_deployment/env/pagopa-stag/terraform.tfvars, src/05_elastic_secret/README.md, src/05_elastic_secret/secret/pagopa-uat/noedit_secret_enc.json, src/06_elastic_resources_common/env/pagopa-dev/terraform.tfvars, src/06_elastic_resources_common/env/pagopa-uat/terraform.tfvars, src/07_elastic_resources_app/04_ilm.tf, src/07_elastic_resources_app/99_variables.tf, src/07_elastic_resources_app/README.md, src/07_elastic_resources_app/env/pagopa-dev/terraform.tfvars, src/07_elastic_resources_app/env/pagopa-uat/terraform.tfvars
=> feat: Prepared uat env

src/06_elastic_resources_common/env/pagopa-uat/terraform.tfvars
=> feat: Fix collector pagopa uat

src/04_elastic_deployment/configs/es.yml.tpl
=> feat: Fix federation

src/06_elastic_resources_common/02_role_definitions.tf, src/06_elastic_resources_common/99_locals.tf, src/06_elastic_resources_common/env/pagopa-uat/terraform.tfvars
=> feat: Fixed space permission

src/06_elastic_resources_deployment/custom_resources/ilm/w1-c3-d5.json, src/06_elastic_resources_deployment/env/pagopa-stag/terraform.tfvars
=> feat: Shortened staging warm phase default

src/04_elastic_deployment/env/pagopa-stag/terraform.tfvars
=> feat: Added third hot node for pagopa staging

src/04_elastic_deployment/env/pagopa-stag/terraform.tfvars
=> feat: Reduced master size

src/06_elastic_resources_common/env/pagopa-uat/terraform.tfvars
=> feat: Moved otel collector ns

src/06_elastic_resources_common/02_role_definitions.tf, src/06_elastic_resources_common/06_open_telemetry.tf, src/06_elastic_resources_common/99_locals.tf, src/06_elastic_resources_common/99_main.tf, src/06_elastic_resources_common/README.md, src/07_elastic_resources_app/99_main.tf, src/07_elastic_resources_app/README.md
=> feat: PAYMCLOUD-243 segregated apm indices

src/06_elastic_resources_common/99_locals.tf
=> feat: Restored marco.mari as admin

src/06_elastic_resources_common/env/pagopa-dev/terraform.tfvars, src/06_elastic_resources_common/env/pagopa-prod/terraform.tfvars, src/06_elastic_resources_common/env/pagopa-uat/terraform.tfvars, src/07_elastic_resources_app/env/pagopa-dev/terraform.tfvars, src/07_elastic_resources_app/env/pagopa-prod/terraform.tfvars, src/07_elastic_resources_app/env/pagopa-uat/terraform.tfvars, src/07_elastic_resources_app/products/pagopa/checkout/checkout/appSettings.json
=> feat(space): add checkout space

src/06_elastic_resources_common/99_main.tf, src/06_elastic_resources_common/README.md
=> feat: Updated elastic module

src/06_elastic_resources_common/env/pagopa-prod/terraform.tfvars, src/07_elastic_resources_app/default_library/ilm/w3-c8-d30.json, src/07_elastic_resources_app/default_library/ilm/w3-c8-d90.json, src/07_elastic_resources_app/products/pagopa/ecommerce/ecommerce/appSettings.json
=> feat: Pagopa prod migration

src/06_elastic_resources_common/env/pagopa-prod/terraform.tfvars
=> feat: Moved pagopa prod otel namespace

src/06_elastic_resources_common/env/pagopa-dev/terraform.tfvars, src/07_elastic_resources_app/products/pagopa/fdr/fdr/appSettings.json
=> chore(pagopa): Update fdr service references in appSettings.json

src/06_elastic_resources_deployment/custom_resources/ilm/w2-c8-d30.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c8-d90.json, src/06_elastic_resources_deployment/env/pagopa-prod/terraform.tfvars
=> feat: Shotened warm phase for apm log prod

src/06_elastic_resources_deployment/01_default_ilm.tf, src/06_elastic_resources_deployment/02_default_template_customization.tf, src/06_elastic_resources_deployment/99_locals.tf, src/06_elastic_resources_deployment/README.md, src/06_elastic_resources_deployment/custom_resources/ilm/w1-c3-d5.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c4-d5.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c4-d7.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c8-d30.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c8-d90.json
=> feat: Updated ilm configuration, changed default ilm name to avoid conflicts

src/07_elastic_resources_app/default_library/ilm/w2-c4-d5.json, src/07_elastic_resources_app/default_library/ilm/w2-c4-d7.json, src/07_elastic_resources_app/default_library/ilm/w3-c8-d30.json, src/07_elastic_resources_app/default_library/ilm/w3-c8-d90.json
=> feat: Updated app ilm

src/06_elastic_resources_deployment/custom_resources/index_template/metricbeat_settings.json
=> feat: Updated metricbeat index template

src/07_elastic_resources_app/env/pagopa-dev/terraform.tfvars, src/07_elastic_resources_app/env/pagopa-prod/terraform.tfvars, src/07_elastic_resources_app/env/pagopa-uat/terraform.tfvars, src/07_elastic_resources_app/products/pagopa/afm/afm/appSettings.json, src/07_elastic_resources_app/products/pagopa/apiconfig/apiconfig/appSettings.json, src/07_elastic_resources_app/products/pagopa/bizevents/bizevents/appSettings.json, src/08_elastic_resources_integration/env/pagopa-dev/terraform.tfvars, src/08_elastic_resources_integration/env/pagopa-prod/terraform.tfvars, src/08_elastic_resources_integration/env/pagopa-uat/terraform.tfvars
=> feat: Added missing microservice spaces

src/04_elastic_deployment/configs/kb.yml.tpl
=> feat: Added reporting roles

src/06_elastic_resources_deployment/01_default_ilm.tf, src/06_elastic_resources_deployment/02_default_template_customization.tf, src/06_elastic_resources_deployment/README.md
=> feat: Added elastic-cloud-logs dedicated lifecycle

src/07_elastic_resources_app/products/pagopa/fdr/fdr/appSettings.json, src/08_elastic_resources_integration/env/pagopa-dev/terraform.tfvars, src/08_elastic_resources_integration/env/pagopa-prod/terraform.tfvars, src/08_elastic_resources_integration/env/pagopa-uat/terraform.tfvars
=> chore: Fix fdr-2-evhub ingestion pipeline

src/06_elastic_resources_deployment/01_default_ilm.tf, src/06_elastic_resources_deployment/02_default_template_customization.tf, src/06_elastic_resources_deployment/03_metricbeat_index_template.tf, src/06_elastic_resources_deployment/99_variables.tf, src/06_elastic_resources_deployment/README.md, src/06_elastic_resources_deployment/env/pagopa-prod/terraform.tfvars, src/06_elastic_resources_deployment/env/pagopa-stag/terraform.tfvars
=> feat: Shorten metricbeat lifecycle

src/04_elastic_deployment/env/pagopa-stag/terraform.tfvars
=> feat: Aligned code with upgraded configuration

src/06_elastic_resources_deployment/99_variables.tf, src/06_elastic_resources_deployment/env/pagopa-prod/terraform.tfvars, src/06_elastic_resources_deployment/env/pagopa-stag/terraform.tfvars
=> feat: Changed default node memory usage alert

src/06_elastic_resources_deployment/02_default_template_customization.tf, src/06_elastic_resources_deployment/04_alert_action_connectors.tf, src/06_elastic_resources_deployment/04_alerts.tf, src/06_elastic_resources_deployment/99_variables.tf, src/06_elastic_resources_deployment/README.md, src/06_elastic_resources_deployment/custom_resources/index_component/lifecycle-and-shard@custom.json, src/06_elastic_resources_deployment/env/pagopa-prod/terraform.tfvars, src/06_elastic_resources_deployment/env/pagopa-stag/terraform.tfvars
=> feat: Update traces sharding

src/06_elastic_resources_deployment/04_alerts.tf
=> feat: Updated alert message for better filtering

src/07_elastic_resources_app/products/pagopa/afm/afm/appSettings.json, src/07_elastic_resources_app/products/pagopa/apiconfig/apiconfig/appSettings.json, src/07_elastic_resources_app/products/pagopa/bizevents/bizevents/appSettings.json, src/07_elastic_resources_app/products/pagopa/checkout/checkout/appSettings.json, src/07_elastic_resources_app/products/pagopa/fdr/fdr/appSettings.json, src/07_elastic_resources_app/products/pagopa/gps/pagopapaymentspull/appSettings.json, src/07_elastic_resources_app/products/pagopa/printit/printit/appSettings.json
=> feat: Cleanup unused datastream

src/07_elastic_resources_app/02_elastic_app_resources.tf, src/07_elastic_resources_app/99_main.tf, src/07_elastic_resources_app/99_variables.tf, src/07_elastic_resources_app/README.md, src/07_elastic_resources_app/default_library/index_component/basic-pipeline-lifecycle-shard@custom.json, src/07_elastic_resources_app/env/pagopa-prod/terraform.tfvars, src/07_elastic_resources_app/products/pagopa/ecommerce/ecommerce/appSettings.json
=> feat: Updated ecommerce sharding

README.md
=> chore: Added doc references

src/07_elastic_resources_app/products/pagopa/ndp/pagopawispconverter/appSettings.json, src/08_elastic_resources_integration/env/pagopa-dev/terraform.tfvars
=> fix(pagopawispconverter): update display name and ingest pipeline

src/06_elastic_resources_deployment/01_default_ilm.tf, src/06_elastic_resources_deployment/custom_resources/ilm/w1-c3-d5.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c4-d5.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c4-d7.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c8-d30.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c8-d90.json, src/07_elastic_resources_app/04_ilm.tf, src/07_elastic_resources_app/default_library/ilm/w2-c4-d5.json, src/07_elastic_resources_app/default_library/ilm/w2-c4-d7.json, src/07_elastic_resources_app/default_library/ilm/w2-c8-d30.json, src/07_elastic_resources_app/default_library/ilm/w2-c8-d90.json, src/07_elastic_resources_app/default_library/ilm/w3-c8-d30.json, src/07_elastic_resources_app/default_library/ilm/w3-c8-d90.json
=> feat: PAYMCLOUD-413 removed replica from cold storage

src/08_elastic_resources_integration/env/pagopa-dev/terraform.tfvars, src/08_elastic_resources_integration/env/pagopa-prod/terraform.tfvars, src/08_elastic_resources_integration/env/pagopa-uat/terraform.tfvars
=> feat(log): add pagopa-jwt-issuer service to ecommerce domain [CHK-4188] 

src/06_elastic_resources_deployment/02_default_template_customization.tf, src/07_elastic_resources_app/01_override_apm_index_template.tf, src/07_elastic_resources_app/default_library/index_component/basic-lifecycle-shard@custom.json, src/07_elastic_resources_app/products/pagopa/fdr/fdr/appSettings.json
=> feat: Shard tuning

src/04_elastic_deployment/env/pagopa-stag/terraform.tfvars
=> feat: Increased staging master size, decreased cold

src/06_elastic_resources_deployment/01_default_ilm.tf, src/06_elastic_resources_deployment/custom_resources/ilm/w1-c3-d5-minsize-shrink.json, src/06_elastic_resources_deployment/custom_resources/ilm/w1-c3-d5-shrink.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c4-d7-minsize-shrink.json, src/06_elastic_resources_deployment/custom_resources/ilm/w2-c8-d90-shrink.json, src/07_elastic_resources_app/04_ilm.tf, src/07_elastic_resources_app/default_library/ilm/w2-c4-d5-minsize-shrink.json, src/07_elastic_resources_app/default_library/ilm/w2-c4-d7-shrink.json, src/07_elastic_resources_app/default_library/ilm/w2-c8-d30-shrink.json, src/07_elastic_resources_app/default_library/ilm/w2-c8-d90-shrink.json
=> feat: Tuned shrink size

src/07_elastic_resources_app/99_main.tf, src/07_elastic_resources_app/README.md
=> chore: Upgrade v4 version

src/04_elastic_deployment/env/pagopa-prod/terraform.tfvars
=> feat: Switched prod to cpu optimized

src/04_elastic_deployment/env/pagopa-stag/terraform.tfvars
=> feat: Configured staging hardware profile

src/06_elastic_resources_deployment/.terraform.lock.hcl, src/06_elastic_resources_deployment/99_main.tf, src/06_elastic_resources_deployment/README.md
=> feat: Updated elasticstack provider for alerts

src/06_elastic_resources_deployment/04_alerts.tf
=> feat: Tuned alert frequencies
